language: ruby
rvm:
  - 2.5
  - 2.6
matrix:
  include:
    - rvm: 2.5
      os: osx
    - rvm: 2.6
      os: osx
before_script:
- rvm install ruby-2.4.6
- npm install -g typescript
script: npm run test
